[package]
name = "financial-ops"
version = "1.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Kevin Rodriguez <_@kevinrodriguez.io>"]
description = "A Rust library to perform decimal arithmetic without floating point values."
license = "MIT"
repository = "https://github.com/kevinrodriguez-io/financial-ops"
homepage = "https://github.com/kevinrodriguez-io/financial-ops"
documentation = "https://docs.rs/financial-ops"
readme = "README.md"
keywords = [
    "blockchain",
    "financial",
    "solana",
    "mint",
    "finance",
]
categories = ["finance", "cryptography"]

[dependencies]
financial-ops-macros = { version = "1.1.0", path = "../financial-ops-macros" }
